development:
  host: localhost
  adapter: mysql2
  encoding: utf8
  database: simplecompany
  username: admin
  password: admin
  pool: 5
  timeout: 5000

test:
  host: 127.0.0.1
  adapter: mysql2
  encoding: utf8
  database: test-simplecompany
  username: root
  password: admin
  pool: 5
  timeout: 5000

development:
  host: localhost
  adapter: mysql2
  encoding: utf8
  database: simplecompany
  username: admin
  password: admin
  pool: 5
  timeout: 5000
